In [1]:
import numpy as np
import pandas as pd

In [2]:
file = pd.read_csv('XLSX - No XLS/Alphabet Inc (GOOG)/2016-06-30-0.csv')

In [3]:
file

,CONSOLIDATED BALANCE SHEETS - USD ($) $ in Millions,"Jun. 30, 2016","Dec. 31, 2015"
0,Current assets:,NaN,NaN
1,Cash and cash equivalents,13627,16549
2,Marketable securities,64833,56517
3,"Total cash, cash equivalents, and marketable s...",78460,73066
4,"Accounts receivable, net of allowance of $296 ...",11686,11556
5,Receivable under reverse repurchase agreements,500,450
6,"Income taxes receivable, net",576,1903
7,"Prepaid revenue share, expenses and other assets",3016,3139
8,Total current assets,94238,90114
9,"Prepaid revenue share, expenses and other asse...",3275,3181
10,Non-marketable investments,5820,5183
11,Deferred income taxes,253,251
12,"Property and equipment, net",31413,29016
13,"Intangible assets, net",3452,3847
14,Goodwill,15841,15869
15,Total assets,154292,147461
16,Current liabilities:,NaN,NaN
17,Accounts payable,1716,1931
18,Short-term debt,2219,3225
19,Accrued compensation and benefits,3409,3539
20,Accrued expenses and other current liabilities,4502,4768
21,Accrued revenue share,2345,2329
22,Securities lending payable,2065,2428
23,Deferred revenue,900,788
24,"Income taxes payable, net",185,302
25,Total current liabilities,17341,19310
26,Long-term debt,1984,1995
27,"Deferred revenue, non-current",151,151
28,"Income taxes payable, non-current",4135,3663
29,Deferred income taxes,651,189
30,Other long-term liabilities,2151,1822
31,Total liabilities,26413,27130
32,Commitments and contingencies,,
33,Stockholders’ equity:,NaN,NaN
34,"Convertible preferred stock, $0.001 par value ...",0,0
35,"Class A and Class B common stock, and Class C ...",34293,32982
36,Accumulated other comprehensive loss,-1151,-1874
37,Retained earnings,94737,89223
38,Total stockholders’ equity,127879,120331
39,Total liabilities and stockholders’ equity,154292,147461

In [4]:
file = file.drop(file.columns[2], axis=1)

In [5]:
file = file.set_axis(['2016-06-30-0', 'Default'], axis=1, inplace=False)

In [6]:
file

                                         2016-06-30-0 Default
0                                     Current assets:     NaN
1                           Cash and cash equivalents   13627
2                               Marketable securities   64833
3   Total cash, cash equivalents, and marketable s...   78460
4   Accounts receivable, net of allowance of $296 ...   11686
5      Receivable under reverse repurchase agreements     500
6                        Income taxes receivable, net     576
7    Prepaid revenue share, expenses and other assets    3016
8                                Total current assets   94238
9   Prepaid revenue share, expenses and other asse...    3275
10                         Non-marketable investments    5820
11                              Deferred income taxes     253
12                        Property and equipment, net   31413
13                             Intangible assets, net    3452
14                                           Goodwill   15841
15                                       Total assets  154292
16                               Current liabilities:     NaN
17                                   Accounts payable    1716
18                                    Short-term debt    2219
19                  Accrued compensation and benefits    3409
20     Accrued expenses and other current liabilities    4502
21                              Accrued revenue share    2345
22                         Securities lending payable    2065
23                                   Deferred revenue     900
24                          Income taxes payable, net     185
25                          Total current liabilities   17341
26                                     Long-term debt    1984
27                      Deferred revenue, non-current     151
28                  Income taxes payable, non-current    4135
29                              Deferred income taxes     651
30                        Other long-term liabilities    2151
31                                  Total liabilities   26413
32                      Commitments and contingencies
33                              Stockholders’ equity:     NaN
34  Convertible preferred stock, $0.001 par value ...       0
35  Class A and Class B common stock, and Class C ...   34293
36               Accumulated other comprehensive loss   -1151
37                                  Retained earnings   94737
38                         Total stockholders’ equity  127879
39         Total liabilities and stockholders’ equity  154292

In [7]:
col_one_list = file['2016-06-30-0'].tolist()
#col_one_arr = file['2016-06-30-0'].to_numpy()

print(f"\ncol_one_list:\n{col_one_list}\ntype:{type(col_one_list)}")
#print(f"\ncol_one_arr:\n{col_one_arr}\ntype:{type(col_one_arr)}")

col_one_list:
['Current assets:', 'Cash and cash equivalents', 'Marketable securities', 'Total cash, cash equivalents, and marketable securities (including securities loaned of $4,531 and $4,426)', 'Accounts receivable, net of allowance of $296 and $294', 'Receivable under reverse repurchase agreements', 'Income taxes receivable, net', 'Prepaid revenue share, expenses and other assets', 'Total current assets', 'Prepaid revenue share, expenses and other assets, non-current', 'Non-marketable investments', 'Deferred income taxes', 'Property and equipment, net', 'Intangible assets, net', 'Goodwill', 'Total assets', 'Current liabilities:', 'Accounts payable', 'Short-term debt', 'Accrued compensation and benefits', 'Accrued expenses and other current liabilities', 'Accrued revenue share', 'Securities lending payable', 'Deferred revenue', 'Income taxes payable, net', 'Total current liabilities', 'Long-term debt', 'Deferred revenue, non-current', 'Income taxes payable, non-current', 'Deferred income taxes', 'Other long-term liabilities', 'Total liabilities', 'Commitments and contingencies', 'Stockholders’ equity:', 'Convertible preferred stock, $0.001 par value per share, 100,000 shares authorized; no shares issued and outstanding', 'Class A and Class B common stock, and Class C capital stock and additional paid-in capital, $0.001 par value per share: 15,000,000 shares authorized (Class A 9,000,000, Class B 3,000,000, Class C 3,000,000); 687,348 (Class A 292,297, Class B 50,295, Class C 344,756) and 686,778 (Class A 294,686, Class B 48,921, Class C 343,171) shares issued and outstanding', 'Accumulated other comprehensive loss', 'Retained earnings', 'Total stockholders’ equity', 'Total liabilities and stockholders’ equity']
type:<class 'list'>

In [8]:
#Enter subs
subs00 = 'Marketable securities'
subs01 = 'Cash and cash equivalents'
subs02 = 'Accounts receivable'
subs03 = 'Total current a'
subs04 = 'Total current l'
subs05 = 'Total assets'
subs06 = 'Total liabilities'
subs07 = 'Retained earnings'
subs08 = 'Total stockholder'
subs09 = 'Property'
subs10 = 'Short'
subs11 = 'Long'
subs12 = 'Convertible'
subs13 = 'Class A'

res00 = [i for i in col_one_list if subs00 in i]
print(res00)
res01 = [i for i in col_one_list if subs01 in i]
print(res01)
res02 = [i for i in col_one_list if subs02 in i]
print(res02)
res03 = [i for i in col_one_list if subs03 in i]
print(res03)
res04 = [i for i in col_one_list if subs04 in i]
print(res04)
res05 = [i for i in col_one_list if subs05 in i]
print(res05)
res06 = [i for i in col_one_list if subs06 in i]
print(res06)
res07 = [i for i in col_one_list if subs07 in i]
print(res07)
res08 = [i for i in col_one_list if subs08 in i]
print(res08)
res09 = [i for i in col_one_list if subs09 in i]
print(res09)
res10 = [i for i in col_one_list if subs10 in i]
print(res10)
res11 = [i for i in col_one_list if subs11 in i]
print(res11)
res12 = [i for i in col_one_list if subs12 in i]
print(res12)
res13 = [i for i in col_one_list if subs13 in i]
print(res13)

['Marketable securities']
['Cash and cash equivalents']
['Accounts receivable, net of allowance of $296 and $294']
['Total current assets']
['Total current liabilities']
['Total assets']
['Total liabilities', 'Total liabilities and stockholders’ equity']
['Retained earnings']
['Total stockholders’ equity']
['Property and equipment, net']
['Short-term debt']
['Long-term debt']
['Convertible preferred stock, $0.001 par value per share, 100,000 shares authorized; no shares issued and outstanding']
['Class A and Class B common stock, and Class C capital stock and additional paid-in capital, $0.001 par value per share: 15,000,000 shares authorized (Class A 9,000,000, Class B 3,000,000, Class C 3,000,000); 687,348 (Class A 292,297, Class B 50,295, Class C 344,756) and 686,778 (Class A 294,686, Class B 48,921, Class C 343,171) shares issued and outstanding']

In [9]:
file.replace(res00, 
           "Marketable securities", inplace=True)
file.replace(res01, 
           "Cash and cash equivalents", inplace=True)
file.replace(res02, 
           "Accounts receivable", inplace=True)
file.replace(res03, 
           "Current assets", inplace=True)
file.replace(res04, 
           "Current liabilities", inplace=True)
file.replace(res05, 
           "Total assets", inplace=True)
file.replace(res06, 
           "Total liabilities", inplace=True)
file.replace(res07, 
           "Retained earnings", inplace=True)
file.replace(res08, 
           "Total stockholder's equity", inplace=True)
file.replace(res09, 
           "Property, plant and equipment", inplace=True)
file.replace(res10, 
           "Short-term debt", inplace=True)
file.replace(res11, 
           "Long-term debt", inplace=True)
file.replace(res12, 
           "Convertible stocks", inplace=True)
file.replace(res13, 
           "Class A and Class B stocks", inplace=True)
#file

In [16]:
#file.loc[file['2016-06-30-0'] == 'Marketable securities']
print(file.loc[file['2016-06-30-0'].isin(['Marketable securities',
                                          'Cash and cash equivalents',
                                          'Accounts receivable',
                                          'Current assets',
                                          'Current liabilities',
                                          'Total assets',
                                          'Total liabilities',
                                          'Retained earnings',
                                          "Total stockholder's equity",
                                          'Property, plant and equipment',
                                          'Short-term debt',
                                          'Long-term debt',
                                          'Convertible stocks',
                                         'Class A and Class B stocks'])])

                     2016-06-30-0 Default
1       Cash and cash equivalents   13627
2           Marketable securities   64833
4             Accounts receivable   11686
8                  Current assets   94238
12  Property, plant and equipment   31413
15                   Total assets  154292
18                Short-term debt    2219
25            Current liabilities   17341
26                 Long-term debt    1984
31              Total liabilities   26413
34             Convertible stocks       0
35     Class A and Class B stocks   34293
37              Retained earnings   94737
38     Total stockholder's equity  127879
39              Total liabilities  154292

In [86]:
col_one_arr = file.loc[file['2016-06-30-0'].isin(['Marketable securities',
                                          'Cash and cash equivalents',
                                          'Accounts receivable',
                                          'Current assets',
                                          'Current liabilities',
                                          'Total assets',
                                          'Total liabilities',
                                          'Retained earnings',
                                          "Total stockholder's equity",
                                          'Property, plant and equipment',
                                          'Short-term debt',
                                          'Long-term debt',
                                          'Convertible stocks',
                                         'Class A and Class B stocks'])].to_numpy()

col_one_arr

array([['Cash and cash equivalents', '13627'],
       ['Marketable securities', '64833'],
       ['Accounts receivable', '11686'],
       ['Current assets', '94238'],
       ['Property, plant and equipment', '31413'],
       ['Total assets', '154292'],
       ['Short-term debt', '2219'],
       ['Current liabilities', '17341'],
       ['Long-term debt', '1984'],
       ['Total liabilities', '26413'],
       ['Convertible stocks', '0'],
       ['Class A and Class B stocks', '34293'],
       ['Retained earnings', '94737'],
       ["Total stockholder's equity", '127879'],
       ['Total liabilities', '154292']], dtype=object)

In [104]:
#obj = len(col_one_arr)
#np.insert(col_one_arr, obj, ["PE_1", "PE_1_VALUE"], 0)

new_arr00 = np.append(col_one_arr, [["PE_1", "PE_1_VALUE"]],0)

new_arr01 = np.append(new_arr00, [["PE_1", "PE_1_VALUE"]],0)
new_arr02 = np.append(new_arr01, [["PE_2", "PE_2_VALUE"]],0)
new_arr03 = np.append(new_arr02, [["PEG_1", "PEG_1_VALUE"]],0)
new_arr04 = np.append(new_arr03, [["PEG_2", "PEG_2_VALUE"]],0)
new_arr05 = np.append(new_arr04, [["EV", "EB_VALUE"]],0)
new_arr06 = np.append(new_arr05, [["EBIT", "EBIT_VALUE"]],0)
new_arr07 = np.append(new_arr06, [["EBITDA", "EBITDA_VALUE"]],0)
new_arr08 = np.append(new_arr07, [["DE", "DE_VALUE"]],0)
new_arr09 = np.append(new_arr08, [["NE", "NE_VALUE"]],0)
new_arr10 = np.append(new_arr09, [["QR_1", "QR_1_VALUE"]],0)
new_arr11 = np.append(new_arr10, [["QR_2", "QR_2_VALUE"]],0)

new_arr12 = np.append(new_arr11, [["DY", "DY_VALUE"]],0)
new_arr13 = np.append(new_arr12, [["DPS", "DPS_VALUE"]],0)
new_arr14 = np.append(new_arr13, [["EPS", "EPS_VALUE"]],0)
new_arr15 = np.append(new_arr14, [["MCAP", "MCAP_VALUE"]],0)
new_arr16 = np.append(new_arr15, [["ROE", "ROE_VALUE"]],0)
new_arr17 = np.append(new_arr16, [["NetMargin", "NetMargin_VALUE"]],0)
new_arr18 = np.append(new_arr17, [["OperatingMargin", "OperatingMargin_VALUE"]],0)

new_arr18

array([['Cash and cash equivalents', '13627'],
       ['Marketable securities', '64833'],
       ['Accounts receivable', '11686'],
       ['Current assets', '94238'],
       ['Property, plant and equipment', '31413'],
       ['Total assets', '154292'],
       ['Short-term debt', '2219'],
       ['Current liabilities', '17341'],
       ['Long-term debt', '1984'],
       ['Total liabilities', '26413'],
       ['Convertible stocks', '0'],
       ['Class A and Class B stocks', '34293'],
       ['Retained earnings', '94737'],
       ["Total stockholder's equity", '127879'],
       ['Total liabilities', '154292'],
       ['PE_1', 'PE_1_VALUE'],
       ['PE_1', 'PE_1_VALUE'],
       ['PE_2', 'PE_2_VALUE'],
       ['PEG_1', 'PEG_1_VALUE'],
       ['PEG_2', 'PEG_2_VALUE'],
       ['EV', 'EB_VALUE'],
       ['EBIT', 'EBIT_VALUE'],
       ['EBITDA', 'EBITDA_VALUE'],
       ['DE', 'DE_VALUE'],
       ['NE', 'NE_VALUE'],
       ['QR_1', 'QR_1_VALUE'],
       ['QR_2', 'QR_2_VALUE'],
       ['DY', 'DY_VALUE'],
       ['DPS', 'DPS_VALUE'],
       ['EPS', 'EPS_VALUE'],
       ['MCAP', 'MCAP_VALUE'],
       ['ROE', 'ROE_VALUE'],
       ['NetMargin', 'NetMargin_VALUE'],
       ['OperatingMargin', 'OperatingMargin_VALUE']], dtype=object)